services:

  ipsec-vpn:
    image: hwdsl2/ipsec-vpn-server:latest
    container_name: ipsec-vpn
    # Use host networking so UDP 500/4500 are reachable directly
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_IPSEC_PSK=ipsec-vpn-key
      - VPN_USER=dima
      - VPN_PASSWORD=rabbit
    volumes:
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped

    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=False
    env_file:
      - ./sandbox/.env
    restart: unless-stopped
    networks:
      - my_custom_network

  xray:
    image: teddysun/xray:latest
    container_name: xray
    volumes:
      - ./xray/config.json:/etc/xray/config.json:ro
      - ./xray/logs:/var/log/xray
    ports:
      - "10000:10000"
    restart: unless-stopped
    networks:
      - my_custom_network


networks:
  my_custom_network: